create table "public"."business_phone_numbers" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "phone_number" text,
    "business_id" integer
);


CREATE UNIQUE INDEX business_phone_numbers_pkey ON public.business_phone_numbers USING btree (id);

alter table "public"."business_phone_numbers" add constraint "business_phone_numbers_pkey" PRIMARY KEY using index "business_phone_numbers_pkey";

alter table "public"."business_phone_numbers" add constraint "business_phone_numbers_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_phone_numbers" validate constraint "business_phone_numbers_business_id_fkey";

grant delete on table "public"."business_phone_numbers" to "anon";

grant insert on table "public"."business_phone_numbers" to "anon";

grant references on table "public"."business_phone_numbers" to "anon";

grant select on table "public"."business_phone_numbers" to "anon";

grant trigger on table "public"."business_phone_numbers" to "anon";

grant truncate on table "public"."business_phone_numbers" to "anon";

grant update on table "public"."business_phone_numbers" to "anon";

grant delete on table "public"."business_phone_numbers" to "authenticated";

grant insert on table "public"."business_phone_numbers" to "authenticated";

grant references on table "public"."business_phone_numbers" to "authenticated";

grant select on table "public"."business_phone_numbers" to "authenticated";

grant trigger on table "public"."business_phone_numbers" to "authenticated";

grant truncate on table "public"."business_phone_numbers" to "authenticated";

grant update on table "public"."business_phone_numbers" to "authenticated";

grant delete on table "public"."business_phone_numbers" to "service_role";

grant insert on table "public"."business_phone_numbers" to "service_role";

grant references on table "public"."business_phone_numbers" to "service_role";

grant select on table "public"."business_phone_numbers" to "service_role";

grant trigger on table "public"."business_phone_numbers" to "service_role";

grant truncate on table "public"."business_phone_numbers" to "service_role";

grant update on table "public"."business_phone_numbers" to "service_role";


